import { Subject, Topic, Subtopic, Exam, AppBlockerConfig, Reward, Achievement, Notification, AIInsight, Resource } from '@/types';

export const mockSubjects: Subject[] = [
  {
    id: 'java',
    name: 'Java Programming',
    shortName: 'JAVA',
    color: '#ef4444',
    gradient: ['#ef4444', '#f97316'],
    icon: '☕',
    progress: 80,
    streak: 6,
    topicsTotal: 15,
    topicsCompleted: 12,
    totalHours: 25,
    weakTopics: ['Exception Handling', 'Multithreading'],
    strongTopics: ['OOP Concepts', 'Collections'],
    lastStudied: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'python',
    name: 'Python Programming',
    shortName: 'PYTHON',
    color: '#0ea5e9',
    gradient: ['#0ea5e9', '#8b5cf6'],
    icon: '🐍',
    progress: 65,
    streak: 3,
    topicsTotal: 12,
    topicsCompleted: 8,
    totalHours: 18,
    weakTopics: ['Decorators', 'Async Programming'],
    strongTopics: ['Basics', 'Data Structures'],
    lastStudied: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'javascript',
    name: 'JavaScript & TypeScript',
    shortName: 'JS/TS',
    color: '#f59e0b',
    gradient: ['#f59e0b', '#ef4444'],
    icon: '⚡',
    progress: 45,
    streak: 1,
    topicsTotal: 14,
    topicsCompleted: 6,
    totalHours: 22,
    weakTopics: ['Promises', 'TypeScript Generics'],
    strongTopics: ['ES6+', 'DOM Manipulation'],
    lastStudied: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: 'datastructures',
    name: 'Data Structures & Algorithms',
    shortName: 'DSA',
    color: '#8b5cf6',
    gradient: ['#8b5cf6', '#ec4899'],
    icon: '📊',
    progress: 30,
    streak: 0,
    topicsTotal: 20,
    topicsCompleted: 6,
    totalHours: 30,
    weakTopics: ['Graph Algorithms', 'Dynamic Programming'],
    strongTopics: ['Arrays', 'Linked Lists'],
    lastStudied: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: 'databases',
    name: 'Database Systems',
    shortName: 'DBMS',
    color: '#06b6d4',
    gradient: ['#06b6d4', '#0ea5e9'],
    icon: '🗄️',
    progress: 55,
    streak: 2,
    topicsTotal: 10,
    topicsCompleted: 5,
    totalHours: 15,
    weakTopics: ['Query Optimization', 'Transactions'],
    strongTopics: ['SQL Basics', 'Normalization'],
    lastStudied: new Date(Date.now() - 43200000).toISOString(),
  },
];

export const mockTopics: Record<string, Topic[]> = {
  java: [
    {
      id: 'java-oop',
      subjectId: 'java',
      name: 'Object-Oriented Programming',
      description: 'Master the four pillars of OOP: Encapsulation, Inheritance, Polymorphism, and Abstraction.',
      order: 1,
      isCompleted: true,
      isLocked: false,
      progress: 100,
      estimatedMinutes: 45,
      xpReward: 150,
      subtopics: [
        { id: 'java-classes', topicId: 'java-oop', name: 'Classes & Objects', isCompleted: true, content: 'Classes are blueprints...', duration: 15 },
        { id: 'java-inheritance', topicId: 'java-oop', name: 'Inheritance', isCompleted: true, content: 'Inheritance allows...', duration: 15 },
        { id: 'java-polymorphism', topicId: 'java-oop', name: 'Polymorphism', isCompleted: true, content: 'Polymorphism means...', duration: 15 },
      ],
      quizQuestions: 8,
      resources: [
        { id: 'r1', type: 'video', title: 'OOP Concepts Explained', duration: 20 },
        { id: 'r2', type: 'article', title: 'Java OOP Best Practices', duration: 15 },
      ],
    },
    {
      id: 'java-exceptions',
      subjectId: 'java',
      name: 'Exception Handling',
      description: 'Learn to handle errors gracefully with try-catch, throws, and custom exceptions.',
      order: 2,
      isCompleted: false,
      isLocked: false,
      progress: 35,
      estimatedMinutes: 35,
      xpReward: 120,
      subtopics: [
        { id: 'java-try-catch', topicId: 'java-exceptions', name: 'Try-Catch Blocks', isCompleted: true, content: 'Try-catch...', duration: 12 },
        { id: 'java-throws', topicId: 'java-exceptions', name: 'Throws Keyword', isCompleted: false, content: 'Throws...', duration: 10 },
        { id: 'java-custom', topicId: 'java-exceptions', name: 'Custom Exceptions', isCompleted: false, content: 'Custom...', duration: 13 },
      ],
      quizQuestions: 6,
      resources: [
        { id: 'r3', type: 'video', title: 'Exception Handling Deep Dive', duration: 25 },
      ],
    },
    {
      id: 'java-collections',
      subjectId: 'java',
      name: 'Collections Framework',
      description: 'Master List, Set, Map interfaces and their implementations.',
      order: 3,
      isCompleted: true,
      isLocked: false,
      progress: 100,
      estimatedMinutes: 50,
      xpReward: 180,
      subtopics: [
        { id: 'java-list', topicId: 'java-collections', name: 'ArrayList & LinkedList', isCompleted: true, content: 'Lists...', duration: 15 },
        { id: 'java-set', topicId: 'java-collections', name: 'HashSet & TreeSet', isCompleted: true, content: 'Sets...', duration: 15 },
        { id: 'java-map', topicId: 'java-collections', name: 'HashMap & TreeMap', isCompleted: true, content: 'Maps...', duration: 20 },
      ],
      quizQuestions: 10,
      resources: [],
    },
    {
      id: 'java-multithreading',
      subjectId: 'java',
      name: 'Multithreading & Concurrency',
      description: 'Understand threads, synchronization, executors, and concurrent collections.',
      order: 4,
      isCompleted: false,
      isLocked: false,
      progress: 10,
      estimatedMinutes: 60,
      xpReward: 200,
      subtopics: [
        { id: 'java-threads', topicId: 'java-multithreading', name: 'Thread Basics', isCompleted: false, content: 'Threads...', duration: 15 },
        { id: 'java-sync', topicId: 'java-multithreading', name: 'Synchronization', isCompleted: false, content: 'Sync...', duration: 20 },
        { id: 'java-executors', topicId: 'java-multithreading', name: 'Executor Framework', isCompleted: false, content: 'Executors...', duration: 25 },
      ],
      quizQuestions: 8,
      resources: [],
    },
    {
      id: 'java-streams',
      subjectId: 'java',
      name: 'Streams & Lambdas',
      description: 'Functional programming with Stream API and lambda expressions.',
      order: 5,
      isCompleted: false,
      isLocked: true,
      progress: 0,
      estimatedMinutes: 40,
      xpReward: 150,
      subtopics: [],
      quizQuestions: 6,
      resources: [],
    },
  ],
  python: [
    {
      id: 'python-basics',
      subjectId: 'python',
      name: 'Python Basics',
      description: 'Variables, data types, control flow, and functions.',
      order: 1,
      isCompleted: true,
      isLocked: false,
      progress: 100,
      estimatedMinutes: 30,
      xpReward: 100,
      subtopics: [],
      quizQuestions: 5,
      resources: [],
    },
    {
      id: 'python-oop',
      subjectId: 'python',
      name: 'OOP in Python',
      description: 'Classes, inheritance, magic methods, and dataclasses.',
      order: 2,
      isCompleted: true,
      isLocked: false,
      progress: 100,
      estimatedMinutes: 40,
      xpReward: 130,
      subtopics: [],
      quizQuestions: 6,
      resources: [],
    },
  ],
  javascript: [],
  datastructures: [],
  databases: [],
};

export const mockExams: Exam[] = [
  {
    id: 'exam-1',
    name: 'Java Programming Final',
    subject: 'Java Programming',
    date: '2026-09-03',
    time: '10:00',
    location: 'Room 301, CS Building',
    progress: 80,
    topicsTotal: 15,
    topicsCompleted: 12,
    color: '#ef4444',
    icon: '☕',
    isActive: true,
  },
  {
    id: 'exam-2',
    name: 'Data Structures Midterm',
    subject: 'Data Structures & Algorithms',
    date: '2026-09-10',
    time: '14:00',
    location: 'Room 205, CS Building',
    progress: 30,
    topicsTotal: 20,
    topicsCompleted: 6,
    color: '#8b5cf6',
    icon: '📊',
    isActive: false,
  },
  {
    id: 'exam-3',
    name: 'Database Systems Final',
    subject: 'Database Systems',
    date: '2026-09-15',
    time: '09:00',
    location: 'Room 101, CS Building',
    progress: 55,
    topicsTotal: 10,
    topicsCompleted: 5,
    color: '#06b6d4',
    icon: '🗄️',
    isActive: false,
  },
];

export const mockBlockedApps: AppBlockerConfig[] = [
  { id: 'instagram', name: 'Instagram', packageName: 'com.instagram.android', icon: '📷', isBlocked: true, category: 'social' },
  { id: 'youtube', name: 'YouTube', packageName: 'com.google.android.youtube', icon: '▶️', isBlocked: true, category: 'entertainment' },
  { id: 'tiktok', name: 'TikTok', packageName: 'com.zhiliaoapp.musically', icon: '🎵', isBlocked: true, category: 'social' },
  { id: 'netflix', name: 'Netflix', packageName: 'com.netflix.mediaclient', icon: '🎬', isBlocked: true, category: 'entertainment' },
  { id: 'spotify', name: 'Spotify', packageName: 'com.spotify.music', icon: '🎵', isBlocked: false, category: 'entertainment' },
  { id: 'discord', name: 'Discord', packageName: 'com.discord', icon: '💬', isBlocked: true, category: 'social' },
  { id: 'games', name: 'Games', packageName: 'com.android.games', icon: '🎮', isBlocked: true, category: 'gaming' },
  { id: 'reddit', name: 'Reddit', packageName: 'com.reddit.frontpage', icon: '🔴', isBlocked: false, category: 'social' },
];

export const mockRewards: Reward[] = [
  { id: 'reward-1', name: 'Instagram', appName: 'Instagram', packageName: 'com.instagram.android', icon: '📷', durationMinutes: 15, xpCost: 200, category: 'social', isUnlocked: true, isActive: false, earnedAt: new Date(Date.now() - 86400000).toISOString() },
  { id: 'reward-2', name: 'YouTube', appName: 'YouTube', packageName: 'com.google.android.youtube', icon: '▶️', durationMinutes: 20, xpCost: 300, category: 'entertainment', isUnlocked: true, isActive: false, earnedAt: new Date(Date.now() - 43200000).toISOString() },
  { id: 'reward-3', name: 'Gaming', appName: 'Games', packageName: 'com.android.games', icon: '🎮', durationMinutes: 10, xpCost: 150, category: 'gaming', isUnlocked: false, isActive: false },
  { id: 'reward-4', name: 'Netflix', appName: 'Netflix', packageName: 'com.netflix.mediaclient', icon: '🎬', durationMinutes: 30, xpCost: 400, category: 'entertainment', isUnlocked: false, isActive: false },
  { id: 'reward-5', name: 'TikTok', appName: 'TikTok', packageName: 'com.zhiliaoapp.musically', icon: '🎵', durationMinutes: 15, xpCost: 200, category: 'social', isUnlocked: false, isActive: false },
  { id: 'reward-6', name: 'Discord', appName: 'Discord', packageName: 'com.discord', icon: '💬', durationMinutes: 20, xpCost: 250, category: 'social', isUnlocked: false, isActive: false },
];

export const mockAchievements: Achievement[] = [
  { id: 'ach-1', name: 'First Steps', description: 'Complete your first topic', icon: '🎯', color: '#0ea5e9', xpReward: 100, requirement: { type: 'topics', value: 1 }, isUnlocked: true, unlockedAt: new Date(Date.now() - 604800000).toISOString(), progress: 1, maxProgress: 1 },
  { id: 'ach-2', name: 'Week Warrior', description: 'Maintain a 7-day study streak', icon: '🔥', color: '#ef4444', xpReward: 500, requirement: { type: 'streak', value: 7 }, isUnlocked: false, progress: 6, maxProgress: 7 },
  { id: 'ach-3', name: 'Quiz Master', description: 'Complete 50 quizzes', icon: '🧠', color: '#8b5cf6', xpReward: 300, requirement: { type: 'quizzes', value: 50 }, isUnlocked: false, progress: 23, maxProgress: 50 },
  { id: 'ach-4', name: 'Focus Champion', description: 'Complete 100 focus sessions', icon: '⏱️', color: '#22c55e', xpReward: 400, requirement: { type: 'focus_hours', value: 100 }, isUnlocked: false, progress: 34, maxProgress: 100 },
  { id: 'ach-5', name: 'Century Scholar', description: 'Complete 100 topics', icon: '📚', color: '#f59e0b', xpReward: 1000, requirement: { type: 'topics', value: 100 }, isUnlocked: false, progress: 56, maxProgress: 100 },
  { id: 'ach-6', name: 'Exam Warrior', description: 'Score 90%+ on 5 mock tests', icon: '🏆', color: '#ec4899', xpReward: 500, requirement: { type: 'perfect_score', value: 5 }, isUnlocked: false, progress: 2, maxProgress: 5 },
  { id: 'ach-7', name: 'Early Bird', description: 'Study before 8 AM for 10 days', icon: '🌅', color: '#f97316', xpReward: 200, requirement: { type: 'early_bird', value: 10 }, isUnlocked: false, progress: 3, maxProgress: 10 },
  { id: 'ach-8', name: 'Night Owl', description: 'Study after 10 PM for 10 days', icon: '🦉', color: '#6366f1', xpReward: 200, requirement: { type: 'night_owl', value: 10 }, isUnlocked: false, progress: 7, maxProgress: 10 },
];

export const mockNotifications: Notification[] = [
  { id: 'notif-1', type: 'exam_reminder', title: 'Java Exam in 5 Days', message: 'Your Java Programming exam is in 5 days. Complete 2 topics today to stay on track.', data: { examId: 'exam-1' }, isRead: false, createdAt: new Date(Date.now() - 3600000).toISOString() },
  { id: 'notif-2', type: 'streak_reminder', title: 'Streak at Risk!', message: 'Your 6-day streak will break if you don\'t study today. Just 15 minutes keeps it alive!', data: {}, isRead: false, createdAt: new Date(Date.now() - 7200000).toISOString() },
  { id: 'notif-3', type: 'reward_unlocked', title: 'Reward Unlocked!', message: 'You earned 15 minutes of Instagram time! Check your Reward Vault.', data: { rewardId: 'reward-1' }, isRead: true, createdAt: new Date(Date.now() - 86400000).toISOString() },
  { id: 'notif-4', type: 'weak_topic', title: 'Weak Topic Alert', message: 'Exception Handling accuracy dropped 18%. AI recommends a revision session.', data: { topicId: 'java-exceptions' }, isRead: false, createdAt: new Date(Date.now() - 10800000).toISOString() },
  { id: 'notif-5', type: 'achievement', title: 'Achievement Unlocked!', message: '🏆 First Steps - Complete your first topic (+100 XP)', data: { achievementId: 'ach-1' }, isRead: true, createdAt: new Date(Date.now() - 604800000).toISOString() },
];

export const mockAIInsights: AIInsight[] = [
  {
    id: 'insight-1',
    type: 'strength',
    title: 'Strong Foundation',
    message: "You're excelling in Object-Oriented Programming with 94% accuracy. Your understanding of inheritance and polymorphism is solid.",
    subjectId: 'java',
    priority: 'high',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    isRead: false,
  },
  {
    id: 'insight-2',
    type: 'weakness',
    title: 'Attention Needed',
    message: 'Your performance in Exception Handling has dropped by 18% this week. Recommend a 20-minute revision session followed by a 5-question quiz.',
    subjectId: 'java',
    topicId: 'java-exceptions',
    action: { type: 'study_topic', targetId: 'java-exceptions', label: 'Start Revision' },
    priority: 'high',
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    isRead: false,
  },
  {
    id: 'insight-3',
    type: 'recommendation',
    title: 'Optimal Study Time',
    message: 'Based on your patterns, you retain 23% more information during 9-11 AM sessions. Consider scheduling difficult topics then.',
    priority: 'medium',
    createdAt: new Date(Date.now() - 21600000).toISOString(),
    isRead: false,
  },
  {
    id: 'insight-4',
    type: 'celebration',
    title: 'Streak Milestone!',
    message: '6-day streak achieved! You\'ve studied 4.2 hours more than last week. Keep the momentum going!',
    priority: 'low',
    createdAt: new Date().toISOString(),
    isRead: false,
  },
];